[project]
name = "dev-activity-report"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gitpython>=3.1.43",
    "prettytable>=3.12.0",
]
